import 'package:flutter/material.dart';
import 'constants.dart';

var textTitle      = TextStyle(fontWeight: FontWeight.bold, fontSize: 17);
var textTitleWhite = TextStyle(fontWeight: FontWeight.bold, fontSize: 17, color: Colors.white);
var textHeadline   = TextStyle(fontWeight: FontWeight.bold, fontSize: 20);
var textHeadlineWhite = TextStyle(fontWeight: FontWeight.bold, fontSize: 20, color: Colors.white);
var textHeadlineL  = TextStyle(fontWeight: FontWeight.bold, fontSize: 24);
var textHeadlineLWhite = TextStyle(fontWeight: FontWeight.bold, fontSize: 24, color: Colors.white);
var textHeadlineXL = TextStyle(fontWeight: FontWeight.bold, fontSize: 28);
var textHeadlineXLWhite = TextStyle(fontWeight: FontWeight.bold, fontSize: 28, color: Colors.white);
var textLabel      = TextStyle(fontWeight: FontWeight.bold, fontSize: 14);
var textLabelWhite = TextStyle(fontWeight: FontWeight.bold, fontSize: 14, color: Colors.white);
var textButton     = TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: Colors.white);
var textButtonL    = TextStyle(fontWeight: FontWeight.bold, fontSize: 18, color: Colors.white);
var textButtonXL   = TextStyle(fontWeight: FontWeight.bold, fontSize: 20, color: Colors.white);
var textMuted      = TextStyle(color: Colors.grey);
var textWhite      = TextStyle(color: Colors.white);
var textMutedS     = TextStyle(fontSize: 12, color: Colors.grey);
var textWhiteS     = TextStyle(fontSize: 12, color: Colors.white);
var textWhite54S   = TextStyle(fontSize: 12, color: Colors.white54);
var textWhite70S   = TextStyle(fontSize: 12, color: Colors.white70);
var textS          = TextStyle(fontSize: 12);
var textLink       = TextStyle(color: THEME_COLOR);
var textInput      = TextStyle(fontSize: 15, color: Colors.grey[850]);
var textInputL     = TextStyle(fontSize: 17, color: Colors.grey[850]);
var textInputXL    = TextStyle(fontSize: 20, color: Colors.grey[850]);
var textHint       = TextStyle(fontSize: 15, color: Colors.grey);

var heightButton   = 44.0;
var heightButtonL  = 50.0;